# This file was generated by GoReleaser. DO NOT EDIT.
cask "nn" do
  version "0.33.1"

  on_macos do
    on_intel do
      sha256 "1fe08c981a7a15246e617f824f98628d2b441e19a935f70932a3c1fa84c269ae"
      url "https://github.com/jaresty/nn/releases/download/v#{version}/nn_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b445ea8ef222fbdb538fc5a0069fce3335229639cf1b4f9997b5dc349af82c5b"
      url "https://github.com/jaresty/nn/releases/download/v#{version}/nn_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0c000261f98fa0a7217d94bb9ee477ad309c479b7b3861419d76d779f3653b56"
      url "https://github.com/jaresty/nn/releases/download/v#{version}/nn_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "143bdfc8bd43ef4d484491fa2b10259fbbf2f54d6493088b2b13ab374a1c55e5"
      url "https://github.com/jaresty/nn/releases/download/v#{version}/nn_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nn"
  desc "LLM-driven Zettelkasten CLI"
  homepage "https://github.com/jaresty/nn"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nn"

  # No zap stanza required

end
