# This file was generated by GoReleaser. DO NOT EDIT.
cask "nn" do
  version "0.116.0"

  on_macos do
    on_intel do
      sha256 "8e554b6eaed45b3a70c665c3ad8538a6ad2f1caff0ce8ad53e587ff19d1459cb"
      url "https://github.com/jaresty/nn/releases/download/v#{version}/nn_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a11c74258041d5e100edace88439d08d95dee6c98c5ce5eb3ffc76e07734a449"
      url "https://github.com/jaresty/nn/releases/download/v#{version}/nn_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "53ff3d3b8242b858866d12974b3956700bbfe47a9e9efacde9fda40165a89c76"
      url "https://github.com/jaresty/nn/releases/download/v#{version}/nn_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "80b1665c8c09795e90eadeb456d30e861815ea2f18428c04e5fbf39fafcf4eca"
      url "https://github.com/jaresty/nn/releases/download/v#{version}/nn_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nn"
  desc "LLM-driven Zettelkasten CLI"
  homepage "https://github.com/jaresty/nn"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nn"

  # No zap stanza required

end
