# This file was generated by GoReleaser. DO NOT EDIT.
cask "nn" do
  version "0.209.0"

  on_macos do
    on_intel do
      sha256 "7efaa8d01da2776338ff8e015b161ea1f3784f3ee64e4950c5c7a932d953ebbe"
      url "https://github.com/jaresty/nn/releases/download/v#{version}/nn_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "383aa0899bfb0f163a5c34ee5e5a293f8d6efbe541eca0bf1314fe56f44cc92c"
      url "https://github.com/jaresty/nn/releases/download/v#{version}/nn_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bed9210bb159b5d4540cdbe4a154cb89f5bc27152d78ab81ff0fc814552aab6e"
      url "https://github.com/jaresty/nn/releases/download/v#{version}/nn_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4d97101c080cc8c3250d78c4ec904a4cb4000a188599be251bd2bfe56a6d6423"
      url "https://github.com/jaresty/nn/releases/download/v#{version}/nn_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nn"
  desc "LLM-driven Zettelkasten CLI"
  homepage "https://github.com/jaresty/nn"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nn"

  # No zap stanza required

end
